### ISSUE TITLE
Better author name matching

### ISSUE THREAD

**Issue by remiolsen** [NationalGenomicsInfrastructure/ngipubs#24]
There are some problems with matching the publication authors from the pubmed abstract to what we have registered in the LIMS.
For instance "R. Olsen" in the lims would not match a pubmed author with name "RA. Olsen". 

I'm unsure if this is just a frontend thing or if it does affect publication scoring.

**Comment by ewels** [comment]
Can add to the interface to easily edit alternate name search terms.

**Comment by alneberg** [comment]
Maybe this is an example: https://ngipubs.scilifelab.se/publications.php?id=633

I think it is K.Wiman that should be matched.

**Comment by alneberg** [comment]
As far as my debugging went, it seems like the correct rows are missing in the `publications_xref` table. So it is not only a display problem.... :(

**Comment by alneberg** [comment]
Could be the handling of papers already present in the database that needs to be improved? I found quite a few publications that were added by a search from a different lab since the labs collaborate on the publications. When this publication shows up again, maybe the authors from the new lab is not added?
